# Generated by Django 6.0.6 on 2026-07-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelversion',
            name='accuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='artifact_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='f1_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='roc_auc',
            field=models.FloatField(default=0.0),
        ),
    ]
