# Generated by Django 5.2.15 on 2026-07-06 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataset_manager', '0002_uploadeddataset_categorical_features_and_more'),
        ('training', '0002_modelversion_accuracy_modelversion_artifact_path_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hyperparameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(max_length=100)),
                ('param_value', models.TextField()),
                ('param_type', models.CharField(choices=[('int', 'Integer'), ('float', 'Float'), ('str', 'String'), ('bool', 'Boolean')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ModelComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comparison_result', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelComparisonDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics', models.JSONField(default=dict)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_name', models.CharField(max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('training_time_seconds', models.FloatField(blank=True, null=True)),
                ('validation_metrics', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='modelversion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='modelversion',
            name='algorithm',
            field=models.CharField(choices=[('logistic_regression', 'Logistic Regression'), ('decision_tree', 'Decision Tree'), ('random_forest', 'Random Forest'), ('gradient_boosting', 'Gradient Boosting'), ('xgboost', 'XGBoost')], default='logistic_regression', max_length=50),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='class_distribution',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='confusion_matrix',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='cv_score_mean',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='cv_score_std',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataset_manager.uploadeddataset'),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='feature_importance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='feature_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='hyperparameters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='pr_auc',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='precision',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='preprocessing_pipeline_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='recall',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='target_column',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='modelversion',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('trained', 'Trained'), ('evaluated', 'Evaluated'), ('deployed', 'Deployed'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='modelversion',
            name='version',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='modelversion',
            index=models.Index(fields=['version'], name='training_mo_version_6e932f_idx'),
        ),
        migrations.AddIndex(
            model_name='modelversion',
            index=models.Index(fields=['is_active'], name='training_mo_is_acti_db76bb_idx'),
        ),
        migrations.AddIndex(
            model_name='modelversion',
            index=models.Index(fields=['status'], name='training_mo_status_6abd94_idx'),
        ),
        migrations.AddField(
            model_name='hyperparameter',
            name='model_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='param_entries', to='training.modelversion'),
        ),
        migrations.AddField(
            model_name='modelcomparison',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelcomparison',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataset_manager.uploadeddataset'),
        ),
        migrations.AddField(
            model_name='modelcomparisondetail',
            name='comparison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='training.modelcomparison'),
        ),
        migrations.AddField(
            model_name='modelcomparisondetail',
            name='model_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.modelversion'),
        ),
        migrations.AddField(
            model_name='trainingrun',
            name='model_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_runs', to='training.modelversion'),
        ),
        migrations.AlterUniqueTogether(
            name='hyperparameter',
            unique_together={('model_version', 'param_name')},
        ),
        migrations.AlterUniqueTogether(
            name='modelcomparisondetail',
            unique_together={('comparison', 'model_version')},
        ),
    ]
